// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: persons.sql

package db

import (
	"context"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (
    name, age
) VALUES ($1, $2)
RETURNING id, name, age
`

type CreatePersonParams struct {
	Name string `json:"name"`
	Age  int32  `json:"age"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson, arg.Name, arg.Age)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM persons WHERE name = $1
`

func (q *Queries) DeletePerson(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deletePerson, name)
	return err
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, age FROM persons
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetPerson(ctx context.Context, name string) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, name)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons SET age = $1
WHERE name = $2
RETURNING id, name, age
`

type UpdatePersonParams struct {
	Age  int32  `json:"age"`
	Name string `json:"name"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, updatePerson, arg.Age, arg.Name)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}
